spring:
    application:
        name: java-api-framework
server:
    port: 7001
---
spring:
    profiles: daily
    application:
        name: java-api-framework
server:
    port: 7001
---
spring:
    profiles: prepub
    application:
        name: java-api-framework
server:
    port: 8080
---
spring:
    profiles: prod
    application:
        name: java-api-framework
server:
    port: 80